// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const { log } = require('console')

describe('calculator 45-78', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('calculator 45-78', async function() {
    await driver.get("http://localhost:3000/")
    await driver.findElement(By.linkText("Calculator")).click()
    await driver.findElement(By.css("tr:nth-child(3) > td:nth-child(1) > .button")).click()
    await driver.findElement(By.css("tr:nth-child(3) > td:nth-child(2) > .button")).click()
    await driver.findElement(By.css("tr:nth-child(3) > td:nth-child(4) > .button")).click()
    await driver.findElement(By.css("tr:nth-child(4) > td:nth-child(1) > .button")).click()
    await driver.findElement(By.css("tr:nth-child(4) > td:nth-child(2) > .button")).click()
    await driver.findElement(By.css("tr:nth-child(5) > td:nth-child(3) > .button")).click()
    await driver.findElement(By.id("result")).click()
    // check that text in result is whish input is 45-78=-24    
    let text = await driver.findElement(By.id("result")).getAttribute("value")
    assert.equal(text, "45-78=-33")
  })
})
